### PR TITLE
link styles reworks

### PR DESCRIPTION
**Pull request by BarkinBayzin**
index and forms are complete

### CODE REVIEW

**Comment by mthocur** [comment]
i see "required-field" class is deleted, can you also check and clean unnecessary codes (if any) [in this commit](https://github.com/acikkaynak/deprem-io-frontend/commit/e62d5a492ccc416ab7418abfe7644e77852e2b74) please.

**Comment by BarkinBayzin** [comment]
Unnecessary codes destroyed

**Review by mthocur — CHANGES_REQUESTED** [review]
https://github.com/acikkaynak/deprem-io-frontend/pull/46#issuecomment-1424325758

**Review by mthocur — APPROVED** [review]

**Comment by karasakalmt** [comment]
@BarkinBayzin conflictleri resolve edip mergeleyebilirsin

**Pull request merged**
